services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pos-sql
    environment:
      SA_PASSWORD: "Password@123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - pos-network
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Password@123", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  be:
    build:
      context: ./be-pos-mini
      dockerfile: Dockerfile
    container_name: pos-api
    image: be-pos-mini:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=pos_mini;User Id=sa;Password=Password@123;TrustServerCertificate=True;Encrypt=False;
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - pos-network

volumes:
  sql_data:

networks:
  pos-network:
    driver: bridge
